name: Docker Image Custom CI

on:
  push:
    branches: [ "custom" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        build-args: TARGETPLATFORM=linux/arm64
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dashy:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dashy:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dashy:buildcache,mode=max
